""" idade = int(input("Digite um número: "))

if idade < 12:
    print("Criança")

elif idade >= 12 and idade < 17:
    print("Adolescente")

elif idade >= 18 and idade < 59:
    print("Adulto")

else:
    print("idoso") """

# -------------------- / -------------------- #

""" lado1 = float(input("Digite o primeiro lado: "))
lado2 = float(input("Digite o segundo lado: "))
lado3 = float(input("Digite o terceiro lado: "))

if lado1 == lado2 and lado1 == lado3:
    print('Equilatero')
elif lado1 == lado2 or lado1 == lado3 or lado2 == lado3:
    print('Isósceles')
else:
    print('Escaleno') """

# -------------------- / -------------------- #

""" compra = float(input('Digite o valor da sua compra: '))
desconto = 0
valor_desconto = 0
valor_final = 0

if compra > 500:
    desconto = 15
elif compra >= 300:
    desconto = 1
elif compra > 100:
    desconto = 5
else:
    desconto = 0

valor_final = compra - (desconto * (compra/100))

print(f'Valor da compra: {compra}')
print(f'Desconto: R$ {desconto}%')
print(f'valor desconto: R${compra - valor_final}')
print(F'Valor final: R${valor_final}') """

# -------------------- / -------------------- #

